apiVersion: v1
kind: Service
metadata:
  name: py-sample-svc
  namespace: default
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app: py-sample
