kind: Deployment
apiVersion: apps/v1
metadata:
  name: vue-sample
  namespace: default
  labels:
    app: vue-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vue-sample
  template:
    metadata:
      labels:
        app: vue-sample
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: vue-sample
          image: $IMAGE_NAME
          ports:
            - name: http-80
              containerPort: 80
              protocol: TCP
          resources: { }
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: { }
      affinity: { }
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
