apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-sample
  name: go-sample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-sample
  template:
    metadata:
      labels:
        app: go-sample
    spec:
      containers:
        - name: go-sample
          image: $IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "512Mi"

